name: 'Deploy to AWS S3 with Docker'
description: 'Deploy Static Website to AWS S3 with Docker'
inputs:
  bucket:
    description: 'The S3 bucket to deploy'
    required: true
  bucket-region:
    description: 'Region of S3 bucket to deploy'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'Folder to deploy'
    required: true
outputs:
  website-url:
    description: 'URL of Website'
runs:
  using: 'docker'
  image: 'Dockerfile'