name: 'Upload & Download Artifacts Reusable Flow'
description: 'Upload & Download Artifact'
inputs:
  file-name:
    description: 'Get Artifact Name to Upload'
    required: true
    default: test-report
  file-path:
    description: 'Get Artifact Path to Upload'
    required: true
    default: test.json
  file-name-1:
    description: 'Get Artifact Name to Download'
    required: true
    default: dist-files
  file-path-1:
    description: 'Get Artifact Path to Download'
    required: true
    default: ./dist
runs:
  using: 'composite'
  steps:
    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.file-name }}
        path: ${{ inputs.file-path }}

    - name: Get build artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.file-name-1 }}
        path: ${{ inputs.file-path-1 }}