name: 'Download Artifacts Reusable Flow'
description: 'Download Artifact'
inputs:
  file-name-1:
    description: 'Get Artifact Name to Download'
    required: true
    # default: dist-files
  file-path-1:
    description: 'Get Artifact Path to Download'
    required: true
    # default: dist
runs:
  using: 'composite'
  steps:
    - name: Get build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.file-name-1 }}
        path: ${{ inputs.file-path-1 }}