name: 'Download Artifacts Reusable Flow'
description: 'Download Artifact'
inputs:
  name:
    description: 'Get Artifact Name to Download'
    required: true
  path:
    description: 'Get Artifact Path to Download'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Get build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.file-name-1 }}
        path: ${{ inputs.file-path-1 }}