name: 'Upload Artifacts Reusable Flow'
description: 'Upload Artifact'
inputs:
  file-name:
    description: 'Get Artifact Name to Upload'
    required: true
    default: test-report
  file-path:
    description: 'Get Artifact Path to Upload'
    required: true
    default: test.json
runs:
  using: 'composite'
  steps:
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.file-name }}
        path: ${{ inputs.file-path }}