name: 'Upload Artifacts Reusable Flow'
description: 'Upload Artifact'
inputs:
  name:
    description: 'Get Artifact Name to Upload'
    required: true
  path:
    description: 'Get Artifact Path to Upload'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}