name: 04.Deployment-S3-with-JS 
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & Cache dependencies
        uses: ./.github/actions/cache-dependency-composite
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & Cache dependencies
        uses: ./.github/actions/cache-dependency-composite
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload Tests
        uses: ./.github/actions/upload-artifact-composite
        with:
          name: test-report
          path: test.json 
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & Cache dependencies
        uses: ./.github/actions/cache-dependency-composite
      - name: Build website
        run: npm run build
      - name: Upload Jar
        uses: ./.github/actions/upload-artifact-composite
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Download Jar
        id: jar-down
        uses: ./.github/actions/download-artifact-composite
        with:
          name: dist-files
          path: dist
      - name: Output contents
        run: ls
      - name: Deploy site
        run: echo "Deploying..."
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        uses: ./.github/actions/deploy-s3-js
        with:
          bucket: gha-bkt-2
          bucket-region: us-east-1
          dist-folder: ./dist
      - name: Get Website URL
        run: | 
          echo Live URL: ${{ steps.deploy.outputs.website-url }}